### ISSUE TITLE
Unknown extension type "DS_Store"

### ISSUE THREAD

**Issue by saurabhnanda** [cdepillabout/servant-static-th#12]
It's a hidden file created by Mac OS in many directories. I can be safely ignored for the purpose of this library.

**Comment by cdepillabout** [comment]
Thanks for submitting this.

I'd be happy to accept a PR for this.

**Comment by cdepillabout** [comment]
It would be nice to expose to the user some sort of functionality for ignoring arbitrary files.

This might be somewhat similar to how `.gitignore` files work.
