### ISSUE TITLE
Unknown extension type "map"

### ISSUE THREAD

**Issue by saurabhnanda** [cdepillabout/servant-static-th#13]
These are source-map files for minified / uglified CSS/JS files. There should probably be a config option in the user-facing API which controls whether these files should be served, or not.

**Comment by cdepillabout** [comment]
Hmm, I'm not sure what to do about this.

`servant-static-th` is really meant to be a super-simple way to bundle and serve static assets with a servant application.

If you have an application with complicated assets, possibly wanted control over bundling certain files (or ignoring certain files), it may be better to find a more reliable way to do it than with `servant-static-th`.


--------------------------------------------------------

That said, if you want to send a PR adding support for bundling these source-map files, I'd be happy to merge it in.

**Comment by cdepillabout** [comment]
This was sort of fixed in #15, although I guess there is a bigger request to add a way to tell `servant-static-th` to ignore (and not serve) some file types.

Let's track that in #12.
