### ISSUE TITLE
Building with cabal

### ISSUE THREAD

**Issue by fkellner** [cdepillabout/servant-static-th#7]
Has anybody experience using this package with cabal? 

My problem is that the `FilePath`s can only be resolved if I give the absolute Path, but I would like the package to be self-contained. 
Specifying `data-dir` in the `.cabal` file and accessing the file via `getDataDir` does not work since the files are needed at compile-time, not at runtime.

**Comment by cdepillabout** [comment]
@fkellner Could you give a little more info about what you're trying to do?  Maybe an example that can be used to reproduce your problem?

The example from the top of http://hackage.haskell.org/package/servant-static-th-0.2.2.0/docs/Servant-Static-TH.html uses a relative path:

```haskell
$(createApiAndServerDecs "FrontEndApi" "frontEndServer" "dir")
```

This should be a relative path to the `dir` directory.  Does this not work for you for some reason?

Also, everything within the `$()` is just normal Haskell code (it just happens to be running at compile time), so maybe `getDataDir` is available there?  I don't think I've ever tried that myself.

**Comment by fkellner** [comment]
What I was trying to do was simply the same as the example, but I did not know how to include the static files in the package (it only worked with absolute paths like `/home/user/project/test/dir` but I wanted to be able to specify it like `test/dir`).

Looking at the .cabal file in this repo, I finally found out that the files that I want to include need to be listed with the `extra-source-files` to be accessible via relative path from the project root.

`getDataDir` is available at compile time, but the path that it returns is not created yet.

Thank you for the quick answer! Maybe it would be helpful to add (at least some excerpt from) the .cabal file that is needed to build the example to it.

**Comment by cdepillabout** [comment]
I thought `extra-source-files` was just for the `cabal sdist` command when it was uploading a package to Hackage.  I didn't realize it was required for any package using `cabal`!

If you want to send a PR to add that info to the README (or the Haddocks), I would happily merge it in.
